Try

diff --git a/.github/workflows/string.yml b/.github/workflows/string.yml
--- a/.github/workflows/string.yml
+++ b/.github/workflows/string.yml
@@ -18,11 +18,15 @@ jobs:
       uses: actions/checkout@v3
       
     - name: Check style
-      uses: jidicula/clang-format-action@v4.11.0
-      with:
-        clang-format-version: '16'
-        check-path: 'src'
-        fallback-style: 'Google'
+      run: |
+        brew install clang-format
+        cd src
+        OUTPUT=$(make lint-check)
+        if [[ -n "$OUTPUT" ]]; then
+          echo "$OUTPUT"
+          echo "::error::clang-format found style issues"
+          exit 1
+        fi
 
     - name: Build project
       run: |
